---
- name: Include firewall config tasks
  ansible.builtin.include_tasks: iptables.yml
  when: keycloak_configure_iptables
  tags:
    - firewall

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yml
  tags:
    - systemd
