---
- name: "Install packages: {{ packages_list }}"
  become: true
  ansible.builtin.package:
    name: "{{ packages_list }}"
    state: present
  when:
    - packages_list | default([]) | length > 0
