---
- name: Ensure required package iptables are installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - iptables

- name: "Configure firewall ports for {{ keycloak.service_name }}"
  become: true
  ansible.builtin.iptables:
    destination_port: "{{ item }}"
    action: "insert"
    rule_num: 6 # magic number I forget why
    chain: "INPUT"
    policy: "ACCEPT"
    protocol: tcp
  loop:
    - "{{ keycloak_http_port }}"
    - "{{ keycloak_https_port }}"
    - "{{ keycloak_management_http_port }}"
    - "{{ keycloak_management_https_port }}"
    - "{{ keycloak_jgroups_port }}"
    - "{{ keycloak_ajp_port }}"
