---
- name: Include firewall config tasks
  ansible.builtin.include_tasks: firewalld.yml
  when: keycloak_configure_firewalld
  tags:
    - firewall

- name: Include patch install tasks
  ansible.builtin.include_tasks: rhsso_patch.yml
  when:
    - sso_apply_patches is defined and sso_apply_patches
    - sso_enable is defined and sso_enable
  tags:
    - install
    - patch
