---
- name: "Restart and enable service: {{ keycloak_config.service_name }}"
  ansible.builtin.systemd:
    name: keycloak
    enabled: true
    state: restarted
    daemon_reload: true
  become: "{{ keycloak_restart_require_privilege_escalation | default(true) }}"
  delegate_to: "{{ ansible_play_hosts | first }}"
  run_once: true

- name: "Wait until service becomes active: {{ keycloak_config.service_name }}"
  ansible.builtin.uri:
    url: "{{ keycloak_config.health_url }}"
  register: keycloak_status
  until: keycloak_status.status == 200
  delegate_to: "{{ ansible_play_hosts | first }}"
  run_once: true
  retries: "{{ keycloak_service_start_retries }}"
  delay: "{{ keycloak_service_start_delay }}"

- name: "Restart and enable service (remaining nodes): {{ keycloak_config.service_name }}"
  ansible.builtin.systemd:
    name: keycloak
    enabled: true
    state: restarted
  become: "{{ keycloak_restart_require_privilege_escalation | default(true) }}"
  when: inventory_hostname != ansible_play_hosts | first
