namespace: middleware_automation
name: keycloak
version: "0.2.5"
readme: README.md
authors:
  - Romain Pelisse <rpelisse@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
  - Pavan Kumar Motaparthi <pmotapar@redhat.com>
description: Install and configure a keycloak, or Red Hat Single Sign-on, service.
license_file: "LICENSE"
tags:
  - keycloak
  - redhat
  - rhel
  - rhn
  - sso
dependencies:
  "middleware_automation.redhat_csp_download": ">=1.2.1"
  "middleware_automation.wildfly": ">=0.0.6"
repository: https://github.com/ansible-middleware/keycloak
documentation: https://github.com/ansible-middleware/keycloak
homepage: https://github.com/ansible-middleware/keycloak
issues: https://github.com/ansible-middleware/keycloak/issues
