---
- name: Prepare
  hosts: all
  tasks:
    - name: "Ensure common prepare phase are set."
      ansible.builtin.include_tasks: ../prepare.yml

    - name: Install JDK17
      become: yes
      ansible.builtin.yum:
        name:
          - java-17-openjdk-headless
        state: present

    - name: Link default logs directory
      become: yes
      ansible.builtin.file:
        state: link
        src: /usr/lib/jvm/jre-17-openjdk
        dest: /opt/openjdk
        force: true
