---
- name: Include firewall config tasks
  ansible.builtin.include_tasks: firewalld.yml
  when: keycloak_configure_firewalld
  tags:
    - firewall

- name: "Include fastpackages"
  ansible.builtin.include_tasks: fastpackages.yml
