---
- name: "Start service: {{ keycloak.service_name }}"
  ansible.builtin.systemd:
    name: keycloak
    enabled: true
    state: started
    daemon_reload: true
  become: "{{ keycloak_quarkus_start_require_privilege_escalation | default(true) }}"

- name: "Wait until service becomes active: {{ keycloak.service_name }}"
  ansible.builtin.uri:
    url: "{{ keycloak.health_url }}"
  register: keycloak_quarkus_status
  until: keycloak_quarkus_status.status == 200
  retries: 25
  delay: 10
  when: internal_force_health_check | default(keycloak_quarkus_restart_health_check)
