- name: Create client roles
  middleware_automation.keycloak.keycloak_role:
    name: "{{ item }}"
    realm: "{{ client.realm | default(keycloak_realm_realm) }}"
    client_id: "{{ client.client_id }}"
    auth_client_id: "{{ keycloak_realm_auth_client }}"
    auth_keycloak_url: "{{ keycloak_realm_url }}{{ keycloak_realm_context }}"
    auth_realm: "{{ keycloak_realm_auth_realm }}"
    auth_username: "{{ keycloak_realm_admin_user }}"
    auth_password: "{{ keycloak_realm_admin_password }}"
    state: present
  loop: "{{ client.roles | flatten }}"
  no_log: "{{ keycloak_realm_no_log | default('True') }}"
