---
- name: Converge
  hosts: all
  vars_files:
    - ../group_vars/all/vars.yml
  vars:
    rhn_username: "{{ lookup('env', 'rhn_username') | default('4278e994-7f90-46eb-b99c-90f2815b845f', true) }}"
    rhn_password: "{{ lookup('env', 'rhn_password') | default('AHOLJo08ursGdWVm0F66iDR5Owk0CwpL', true) }}"
    keycloak_quarkus_bootstrap_admin_password: "remembertochangeme"
    keycloak_admin_password: "remembertochangeme"
    keycloak_quarkus_hostname: "http://instance:8080"
    keycloak_config_override_template: custom.xml.j2
    keycloak_http_port: 8081
    keycloak_management_http_port: 19990
    keycloak_service_runas: True
  roles:
    - role: keycloak
