---
- name: Verify first restarted service with health URL, then rest restart in parallel
  block:
    - name: "Restart and enable service on initial host: {{ keycloak.service_name }}"
      ansible.builtin.include_tasks:
        file: restart.yml
        apply:
          delegate_to: "{{ ansible_play_hosts | first }}"
          run_once: true
      vars:
        internal_force_health_check: true

    - name: "Restart and enable service on other hosts: {{ keycloak.service_name }}"
      ansible.builtin.systemd:
        name: "{{ keycloak.service_name }}"
        enabled: true
        state: restarted
        daemon_reload: true
      become: "{{ keycloak_quarkus_restart_require_privilege_escalation | default(true) }}"
      when: inventory_hostname != ansible_play_hosts | first
