---
- name: Converge
  hosts: all
  vars:
    keycloak_quarkus_show_deprecation_warnings: false
    keycloak_quarkus_admin_pass: "remembertochangeme"
    keycloak_admin_password: "remembertochangeme"
    keycloak_quarkus_host: instance
    keycloak_quarkus_log: file
    keycloak_quarkus_log_level: debug
    keycloak_quarkus_log_target: /tmp/keycloak
    keycloak_quarkus_start_dev: true
    keycloak_quarkus_proxy_mode: none
    keycloak_quarkus_offline_install: true
    keycloak_quarkus_download_path: /tmp/keycloak/
  roles:
    - role: keycloak_quarkus
    - role: keycloak_realm
      keycloak_context: ''
      keycloak_client_users:
        - username: TestUser
          password: password
          client_roles:
            - client: TestClient
              role: TestRoleUser
              realm: "{{ keycloak_realm }}"
        - username: TestAdmin
          password: password
          client_roles:
            - client: TestClient
              role: TestRoleUser
              realm: "{{ keycloak_realm }}"
            - client: TestClient
              role: TestRoleAdmin
              realm: "{{ keycloak_realm }}"
      keycloak_realm: TestRealm
      keycloak_clients:
        - name: TestClient
          realm: "{{ keycloak_realm }}"
          public_client: "{{ keycloak_client_public }}"
          web_origins: "{{ keycloak_client_web_origins }}"
          users: "{{ keycloak_client_users }}"
          client_id: TestClient
