---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars:
    sudo_pkg_name: sudo
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        assets:
          - "{{ assets_server }}/sso/7.6.0/rh-sso-7.6.0-server-dist.zip"
          - "{{ assets_server }}/sso/7.6.1/rh-sso-7.6.1-patch.zip"

    - name: Install JDK8
      become: yes
      ansible.builtin.yum:
        name:
          - java-1.8.0-openjdk
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install JDK8
      become: yes
      ansible.builtin.apt:
        name:
          - openjdk-8-jdk
        state: present
      when: ansible_facts['os_family'] == "Debian"
