---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars:
    sudo_pkg_name: sudo
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml

    - debug:
        var: ansible_python_version

    - command: id root
    - command: cat /etc/sudoers

    - lineinfile:
        path: /etc/sudoers
        regexp: '^root'
        line: 'root	ALL=(ALL)	NOPASSWD: ALL'

    - command: cat /etc/sudoers

    - name: "Install iproute"
      become: true
      ansible.builtin.dnf:
        name:
          - iproute
        state: present

    - name: Create controller directory for downloads
      ansible.builtin.file: # noqa risky-file-permissions delegated, uses controller host user
        path: /tmp/keycloak
        state: directory
        mode: '0750'
      delegate_to: localhost
      run_once: true

      #    - name: Download keycloak archive to controller directory
      #      ansible.builtin.get_url: # noqa risky-file-permissions delegated, uses controller host user
      #        url: https://github.com/keycloak/keycloak/releases/download/24.0.5/keycloak-24.0.5.zip
      #        dest: /tmp/keycloak
      #        mode: '0640'
      #      delegate_to: localhost
      #      run_once: true
