---
- name: Prepare
  hosts: all
  gather_facts: yes
  vars:
    sudo_pkg_name: sudo
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        assets:
          - "{{ assets_server }}/sso/7.6.0/rh-sso-7.6.0-server-dist.zip"
          - "{{ assets_server }}/sso/7.6.1/rh-sso-7.6.1-patch.zip"

    - debug:
        var: ansible_python_version

    - debug:
        msg: "{{ ansible_facts.packages[item] }}"
      loop: "{{ ansible_facts.packages | select('search', regex) }}"
      vars:
        regex: 'python*'

    - name: Create controller directory for downloads
      ansible.builtin.file: # noqa risky-file-permissions delegated, uses controller host user
        path: /tmp/keycloak
        state: directory
        mode: '0750'
      delegate_to: localhost
      run_once: true

    - name: Download keycloak archive to controller directory
      ansible.builtin.get_url: # noqa risky-file-permissions delegated, uses controller host user
        url: https://github.com/keycloak/keycloak/releases/download/24.0.5/keycloak-24.0.5.zip
        dest: /tmp/keycloak
        mode: '0640'
      delegate_to: localhost
      run_once: true
