---
- name: Converge
  hosts: all
  vars_files:
    - ../group_vars/all/vars.yml
  vars:
    keycloak_admin_password: "remembertochangeme"
    keycloak_enable: true
    keycloak_offline_install: false
  roles:
    - role: keycloak
    - role: keycloak_realm
      keycloak_realm_url: "http://instance:8080"
      keycloak_realm_context: "/auth"
      keycloak_realm_admin_user: "admin"
      keycloak_realm_admin_password: "remembertochangeme"
      keycloak_realm_realm: TestRealm
      keycloak_realm_clients:
        - name: TestClient
          realm: "{{ keycloak_realm_realm }}"
          public_client: true
          client_id: TestClient
