# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
- name: Retrieve access token
  ansible.builtin.include_tasks:
    file: ../actions/fetch_access_token.yml

- name: Fetch all authentication flows
  ansible.builtin.uri:
    url: "{{ auth_keycloak_url }}/admin/realms/{{ target_realm }}/authentication/flows"
    method: GET
    headers:
      Accept: application/json
      User-agent: Ansible
      Authorization: "Bearer {{ access_token }}"
    return_content: true
  register: keycloak_flows_response
  no_log: true

- name: Extract flow id for alias 'Integration Test Flow - Form Actions'
  ansible.builtin.set_fact:
    test_flow_id: >-
      {{ keycloak_flows_response.json
          | selectattr('alias', 'equalto', 'Integration Test Flow - Form Actions')
          | map(attribute='id')
          | first }}
  no_log: true

- name: Fetch basic flow data for 'Integration Test Flow - Form Actions'
  ansible.builtin.uri:
    url: "{{ auth_keycloak_url }}/admin/realms/{{ target_realm }}/authentication/flows/{{ test_flow_id }}"
    method: GET
    headers:
      Accept: application/json
      User-agent: Ansible
      Authorization: "Bearer {{ access_token }}"
    return_content: true
  register: test_flow_top_level_data
  no_log: true

- name: Assert flow attributes
  ansible.builtin.assert:
    that:
      - test_flow_top_level_data.json.alias == "Integration Test Flow - Form Actions"
      - test_flow_top_level_data.json.providerId == "basic-flow"
      - test_flow_top_level_data.json.topLevel == true
      - test_flow_top_level_data.json.builtIn == false

- name: Fetch flow executions for 'Integration Test Flow - Form Actions'
  ansible.builtin.uri:
    url: "{{ auth_keycloak_url }}/admin/realms/{{ target_realm }}/authentication/flows/Integration%20Test%20Flow%20-%20Form%20Actions/executions"
    method: GET
    headers:
      Accept: application/json
      User-agent: Ansible
      Authorization: "Bearer {{ access_token }}"
    return_content: true
  register: test_flow_executions
  no_log: true

- name: Assert flow executions
  ansible.builtin.assert:
    that:
      - test_flow_executions.json | length == 5
      - test_flow_executions.json[0].displayName == "Integration Test Flow - Form Actions - registration form"
      - test_flow_executions.json[0].requirement == "REQUIRED"
      - test_flow_executions.json[0].index == 0
      - test_flow_executions.json[0].level == 0
      - test_flow_executions.json[0].authenticationFlow == true
      - test_flow_executions.json[1].providerId == "registration-user-creation"
      - test_flow_executions.json[1].requirement == "REQUIRED"
      - test_flow_executions.json[1].index == 0
      - test_flow_executions.json[1].level == 1
      - test_flow_executions.json[1]['authenticationFlow'] is not defined or test_flow_executions.json[1].authenticationFlow == false
      - test_flow_executions.json[2].providerId == "registration-password-action"
      - test_flow_executions.json[2].requirement == "REQUIRED"
      - test_flow_executions.json[2].index == 1
      - test_flow_executions.json[2].level == 1
      - test_flow_executions.json[3].providerId == "registration-recaptcha-action"
      - test_flow_executions.json[3].requirement == "DISABLED"
      - test_flow_executions.json[3].index == 2
      - test_flow_executions.json[3].level == 1
      - test_flow_executions.json[4].providerId == "registration-terms-and-conditions"
      - test_flow_executions.json[4].requirement == "DISABLED"
      - test_flow_executions.json[4].index == 3
      - test_flow_executions.json[4].level == 1
