<!doctype html>
<html>
  <head>
    <title>Keycloak Ansible Collection documentation index</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://ansible-middleware.github.io/keycloak/main/_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="https://ansible-middleware.github.io/keycloak/main/_static/css/theme.css" type="text/css" />
    <link rel="stylesheet" href="https://ansible-middleware.github.io/keycloak/main/_static/ansible-basic-sphinx-ext.css" type="text/css" />
    <script data-url_root="./" id="documentation_options" src="https://ansible-middleware.github.io/keycloak/main/_static/documentation_options.js"></script>
    <script src="https://ansible-middleware.github.io/keycloak/main/_static/jquery.js"></script>
    <script src="https://ansible-middleware.github.io/keycloak/main/_static/underscore.js"></script>
    <script src="https://ansible-middleware.github.io/keycloak/main/_static/doctools.js"></script>
    <script src="https://ansible-middleware.github.io/keycloak/main/_static/js/theme.js"></script>
  </head>

<body class="wy-body-for-nav">
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="#" class="icon icon-home"> Keycloak Ansible Collection</a>
        </div>
      </div>
    </nav>
    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">
      <div class="wy-nav-content">
          <div class="rst-content">
            <div role="navigation" aria-label="Page navigation">
              <ul class="wy-breadcrumbs">
                  <li><a href="#" class="icon icon-home"></a> &raquo;</li>
                  <li>Welcome to Keycloak Collection documentation</li>
                  <li class="wy-breadcrumbs-aside"></li>
              </ul>
              <hr/>
            </div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
             <div itemprop="articleBody">
                <section id="welcome-to-keycloak-collection-documentation">
                  <h1>Welcome to Keycloak Collection documentation<a class="headerlink" href="#welcome-to-keycloak-collection-documentation" title="Permalink to this headline"></a></h1>
                    <div class="toctree-wrapper compound">
                      <p class="caption" role="heading"><span class="caption-text">Pick collection version:</span></p>
                        <ul>
